### ISSUE TITLE
Settings UI Bug

### ISSUE THREAD

**Issue by AntonDzutstsati** [you-apps/ClockYou#300] opened 2024-02-25 14:36 UTC
### Steps to reproduce

1. In Android Developer Options set Smallest Width on 350.
2. Go to the app's Settings and in portrait mode you will see UI bug just like on the picture below.
P.S. Tested on Nokia G10, Screen Resolution - 720x1600.
![Screenshot_20240222-154107](https://github.com/you-apps/ClockYou/assets/74765004/aed2a1ff-63de-462f-8ca3-2f580d01128c)

### Expected behavior

No bugs.

### Actual behavior

Bugged UI in Settings.

### Clock You version

7.1

### Android version

Android 13, Nokia G10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-02-25 14:37
Duplicate of https://github.com/you-apps/ClockYou/issues/286

**Closed by Bnyro** 2024-02-25 14:37 UTC
Labels: bug
