### ISSUE TITLE
World clock improvement list

### ISSUE THREAD

**Issue by PalmTamino** [you-apps/ClockYou#163] opened 2023-09-14 20:52 UTC
### Describe your suggested feature

- Show city name in Bold
- Use capital of country for city name (Beijing for China, not Shanghai)
- The right space is empty, put an analog clock there in the space
- suggest to inspire the design a little from the Xiaomi world clock app 
![Screenshot_2023-09-14-22-51-48-307_com android deskclock](https://github.com/you-apps/ClockYou/assets/36358673/a94c3e9c-85b1-4619-8928-8f7be5133fac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by julianfairfax** [comment] 2023-09-18 04:31
To add to this, names such as New York and Los Angeles currently don't seem to have a space in between them in Clock You. That should be fixed.

**Comment by Bnyro** [comment] 2023-09-18 06:34
1. This doesn't really fit the style of Material You in mye eyes.
2. Duplicate of #122 
3. I don't really see the point of this, the time is already visible in a digital clock, so why add an other one?...
4. Nah, we don't copy the design of other apps.

**Closed by Bnyro** 2023-09-18 06:34 UTC
Labels: enhancement

**Comment by julianfairfax** [comment] 2023-09-18 15:27
> To add to this, names such as New York and Los Angeles currently don't seem to have a space in between them in Clock You. That should be fixed.

What about this?

**Comment by soshial** [comment] 2023-11-19 15:40
Sorry for adding to the closed task, but there is one killer feature that I noticed in Xiaomi and Samsung apps:
It's that I can see how many hours each timezone is **behind** or **ahead** my timezone:

![photo_5393236317179072238_y](https://github.com/you-apps/ClockYou/assets/100644/fcc743ec-2f48-4591-b49d-8249e692ce8f)
