### ISSUE TITLE
Add option to gradually increase volume

### ISSUE THREAD

**Issue by Gamer750** [you-apps/ClockYou#350] opened 2024-06-08 10:10 UTC
### Describe your suggested feature

The alarm volume should increase gradually . 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-06-08 22:03
Duplicate of https://github.com/you-apps/ClockYou/issues/273

**Closed by Bnyro** 2024-06-08 22:03 UTC
Labels: enhancement
